<?php
require_once "Lodgement.php";
class Apartment extends Lodgement
{

    private int $floor;
    private bool $lift;

    public function __construct(float $surface, string $type, float $meterPrice, int $floor, bool $lift)
    {
        parent::__construct($surface, $type, $meterPrice);
        $this->floor=$floor;
        $this->lift=$lift;
        echo "Apartment = ( $surface, $type, $meterPrice, $floor, $lift )\n";
    }

    public function __toString()
    {
        $res = parent::__toString(); // TODO: Change the autogenerated stub
        $res = $res."Etage : $this->floor\n";
        if ($this->lift == True)
        {
            $ascenseur="oui";
        }
        else
        {
            $ascenseur="non";
        }
        $res = $res."Ascenseur : $ascenseur\n";
        return $res;
    }

}